auth_enabled: true

server:
  http_listen_port: 3100
  log_level: info

common:
  path_prefix: /var/loki
  replication_factor: 1

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    region: ap-south-1
    s3: s3://gps-loki-prod
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/index-cache
    shared_store: s3

compactor:
  working_directory: /var/loki/compactor
  shared_store: s3
  compaction_interval: 5m
  retention_enabled: true

limits_config:
  retention_period: 720h
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 6MB
  max_streams_per_user: 500000
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 720h

query_range:
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        timeout: 500ms
        addresses: memcached:11211

runtime_config:
  file: /etc/loki/runtime-overrides.yaml

analytics:
  reporting_enabled: false
