version: "3.9"

networks:
  obsnet:

services:

  memcached:
    image: memcached:1.6
    command: memcached -m 256
    expose: ["11211"]
    networks: [obsnet]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "Zomat@1738"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: http://15.206.208.4/grafana
    volumes:
      - grafana-data:/var/lib/grafana

    expose: ["3000"]
    networks: [obsnet]
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data:
